# Generated by Django 5.0.2 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pswd', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
            ],
        ),
    ]
