# Generated by Django 4.1.4 on 2023-02-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='data',
            new_name='date',
        ),
    ]
